spring:
  application:
    name: mocktest

  sql:
    init:
      encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/mock_test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dbo

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    web:
#      pageable:
#        default-page-size: 20
#        one-indexed-parameters: true
#        page-parameter: page


server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: INFO




mocktest:
  config:
    jwt-secret-key: 5970337336763979244226452948404D635166546A576E5A7234743777217A25
    jwt-access-expiration-ms: 86400000
    jwt-refresh-expiration-ms: 604800000