spring:
  application:
    name: mocktest

  sql:
    init:
      encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/mock_test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dbo

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081


mocktest:
  config:
    jwt-secret-key: 5970337336763979244226452948404D635166546A576E5A7234743777217A25
    jwt-refresh-expiration-ms: 86400000